# Iterator/Generator


In [1]:
def poriniai(iki):
    count = 2
    while count <= iki:
        yield count
        count += 2


In [2]:
skaiciuojam = poriniai(99)

In [3]:
print(next(skaiciuojam))

2


In [4]:
for skaicius in skaiciuojam:
    print(skaicius)

4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [5]:
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b
        

In [6]:
ats = fib(45)
print(list(ats))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733]


In [7]:
kodas = "1149"
def lauziam_koda():
    skaicius = 0
    while skaicius < 10000:
        spejimas = f'{skaicius:04}'
        if spejimas == kodas:
            print(f'{spejimas} yra tai, ko jus ieskote')
            break
        yield spejimas
        skaicius += 1


In [8]:
bandom = lauziam_koda()
while True:
    try:
        print(next(bandom))
    except StopIteration:
        break

0000
0001
0002
0003
0004
0005
0006
0007
0008
0009
0010
0011
0012
0013
0014
0015
0016
0017
0018
0019
0020
0021
0022
0023
0024
0025
0026
0027
0028
0029
0030
0031
0032
0033
0034
0035
0036
0037
0038
0039
0040
0041
0042
0043
0044
0045
0046
0047
0048
0049
0050
0051
0052
0053
0054
0055
0056
0057
0058
0059
0060
0061
0062
0063
0064
0065
0066
0067
0068
0069
0070
0071
0072
0073
0074
0075
0076
0077
0078
0079
0080
0081
0082
0083
0084
0085
0086
0087
0088
0089
0090
0091
0092
0093
0094
0095
0096
0097
0098
0099
0100
0101
0102
0103
0104
0105
0106
0107
0108
0109
0110
0111
0112
0113
0114
0115
0116
0117
0118
0119
0120
0121
0122
0123
0124
0125
0126
0127
0128
0129
0130
0131
0132
0133
0134
0135
0136
0137
0138
0139
0140
0141
0142
0143
0144
0145
0146
0147
0148
0149
0150
0151
0152
0153
0154
0155
0156
0157
0158
0159
0160
0161
0162
0163
0164
0165
0166
0167
0168
0169
0170
0171
0172
0173
0174
0175
0176
0177
0178
0179
0180
0181
0182
0183
0184
0185
0186
0187
0188
0189
0190
0191
0192
0193
0194
0195
0196
0197
0198
0199


In [9]:
def ieskom():
    with open("gen_failui/generatoriui.txt", "r") as failas:
        while True:
            for eilute in failas:
                yield eilute[:-1]


# DEKORATORIAI



In [40]:
def stri_decorator(fn):
    def wrapper(*args, **kwargs):
        for a in args:
            if type(a) != str:
                return "text must be a string"
        return fn(*args, **kwargs)
    return wrapper

In [41]:
@stri_decorator
def return_string(*args):
    return args


In [42]:
return_string("")

('',)

In [43]:
def less_than_two(fn):
    def wrapper(*args, **kwargs):
        if len(args) > 2:
            return "Enter less than 2 parameters"
        return fn(*args)
    return wrapper

In [44]:
@stri_decorator
@less_than_two
def any_function(*args):
    return args

In [45]:
any_function("stringas", "stringiukas")

('stringas', 'stringiukas')

In [51]:
from time import sleep
from functools import wraps

def delay(seconds):
    def delay(fn):
        @wraps(fn)
        def wrapper(*args, **kwargs):
            print(f"function will be delayed for {seconds} seconds. ")
            sleep(seconds)
            return fn(*args, **kwargs)
        return wrapper
    return delay

In [52]:
@delay(2.5)
@stri_decorator
@less_than_two
def any_function(*args):
    return args

In [53]:
any_function("stringas", "stringiukas")

function will be delayed for 2.5 seconds. 


('stringas', 'stringiukas')

### how long does it takes 

In [ ]:
from time import time
def performance(fn):
    def wrapper(*args, **kwargs):
        t1 = time()
        result = fn(*args, **kwargs)
        t2 = time()
        diff = t2 - t1
        # print(f"It took {diff}")
        return result, diff
    return wrapper

In [ ]:
import requests  # importuojame requests
from time import time  # importuojame time modulį

start_time = time()  # fiksuojame starto laiką
r = requests.get('http://www.cnn.com')  # sukuriame http užklausą
print(r.status_code)  # spausdiname status code (200 = OK, 404 = Not Found, ir t.t. galima pasiguglinti http status codes)
end_time = time()  # fiksuojame pabaigos laiką
print(end_time - start_time)  # atspausdiname laiką, per kurį gaovme atsakymą

# NUMPY

In [1]:
import numpy as np

In [4]:
pirmas = np.arange(1,10)
print(pirmas)

[1 2 3 4 5 6 7 8 9]


In [8]:
antras = np.zeros(10)
print(antras)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
trecias = np.ones(10)
trecias

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
ketvirtas = np.ones(10) + 3
ketvirtas

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [14]:
penktas = np.arange(0,102,2)
penktas

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [20]:
change[2,1]

12

In [36]:
change[-1:]

array([[21, 22, 23, 24, 25]])

In [35]:
change[0:3, 0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [33]:
sixth = np.arange(1,26)
change = sixth.reshape(5,5)
change

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
change[1:-1, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [42]:
change[-2:, 0:-2]

array([[16, 17, 18],
       [21, 22, 23]])

In [48]:
trolo = np.random.rand(20)

array([0.08593991, 0.3127147 , 0.31026176, 0.32462699, 0.5040098 ,
       0.07136543, 0.01249324, 0.60335239, 0.73221385, 0.45417201,
       0.07741429, 0.51548049, 0.48712068, 0.35992055, 0.04469814,
       0.54129841, 0.82772673, 0.54359662, 0.37453503, 0.3293201 ])

In [51]:
print(trolo.max(), trolo.argmax())

0.8277267336478586 16


In [52]:
print(trolo.min(), trolo.argmin())

0.012493244105172163 6


In [53]:
trolo.dtype

dtype('float64')

In [57]:
more = np.arange(1,101)
more

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [60]:
more[more>90]


array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [61]:
more[more % 7 == 0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [73]:
np.linspace(0.025,1,40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [ ]:
traukiasi = np.arange(2,1001)
traukiasi

In [81]:
bandomd=traukiasi[(traukiasi ** 0.5) % 1==0].reshape(5,6)
bandomd

array([[  4,   9,  16,  25,  36,  49],
       [ 64,  81, 100, 121, 144, 169],
       [196, 225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576, 625],
       [676, 729, 784, 841, 900, 961]])

# PANDAS 1



In [22]:
import pandas as pd
import numpy as np


In [40]:
df = pd.read_csv('miestai_isvalyti.csv')
df

Miestas    2019    2011    2001    1989    1979    1970    1959  \
0        Vilnius  540919  535631  542287  576747  475825  370153  236100   
1         Kaunas  286763  315993  378650  419745  370000  305600  216850   
2       Klaipėda  147898  162360  192954  202929  176648  140342   89500   
3       Šiauliai  100119  109328  133883  145629  118724   92375   59700   
4      Panevėžys   87148   99690  119749  126483  102303   74497   41100   
..           ...     ...     ...     ...     ...     ...     ...     ...   
98       Dusetos     560     717     914    1184    1357    1600    1806   
99     Kavarskas     528     666     809     972    1113    1191    1287   
100  Smalininkai     446     515     653     758     805     952    1100   
101    Troškūnai     372     451     525     672    1174    1417    1495   
102     Panemunė     210     274     329     398     506     545     539   

       1923    1897  
0    167400  154532  
1     92446   70920  
2     35845   20100  
3     21387   16128  
4     19197   12968  
..      ...     ...  
98     1164    1278  
99     1041    1546  
100    1741       0  
101    1252    1000  
102     637       0  

[103 rows x 10 columns]

In [41]:
add_miestas = df.set_index("Miestas")
add_miestas

2019    2011    2001    1989    1979    1970    1959    1923  \
Miestas                                                                       
Vilnius      540919  535631  542287  576747  475825  370153  236100  167400   
Kaunas       286763  315993  378650  419745  370000  305600  216850   92446   
Klaipėda     147898  162360  192954  202929  176648  140342   89500   35845   
Šiauliai     100119  109328  133883  145629  118724   92375   59700   21387   
Panevėžys     87148   99690  119749  126483  102303   74497   41100   19197   
...             ...     ...     ...     ...     ...     ...     ...     ...   
Dusetos         560     717     914    1184    1357    1600    1806    1164   
Kavarskas       528     666     809     972    1113    1191    1287    1041   
Smalininkai     446     515     653     758     805     952    1100    1741   
Troškūnai       372     451     525     672    1174    1417    1495    1252   
Panemunė        210     274     329     398     506     545     539     637   

               1897  
Miestas              
Vilnius      154532  
Kaunas        70920  
Klaipėda      20100  
Šiauliai      16128  
Panevėžys     12968  
...             ...  
Dusetos        1278  
Kavarskas      1546  
Smalininkai       0  
Troškūnai      1000  
Panemunė          0  

[103 rows x 9 columns]

In [42]:
add_miestas.shape

(103, 9)

In [43]:
naujas = range(1,104)
add_miestas["nr"] = naujas
add_miestas

2019    2011    2001    1989    1979    1970    1959    1923  \
Miestas                                                                       
Vilnius      540919  535631  542287  576747  475825  370153  236100  167400   
Kaunas       286763  315993  378650  419745  370000  305600  216850   92446   
Klaipėda     147898  162360  192954  202929  176648  140342   89500   35845   
Šiauliai     100119  109328  133883  145629  118724   92375   59700   21387   
Panevėžys     87148   99690  119749  126483  102303   74497   41100   19197   
...             ...     ...     ...     ...     ...     ...     ...     ...   
Dusetos         560     717     914    1184    1357    1600    1806    1164   
Kavarskas       528     666     809     972    1113    1191    1287    1041   
Smalininkai     446     515     653     758     805     952    1100    1741   
Troškūnai       372     451     525     672    1174    1417    1495    1252   
Panemunė        210     274     329     398     506     545     539     637   

               1897   nr  
Miestas                   
Vilnius      154532    1  
Kaunas        70920    2  
Klaipėda      20100    3  
Šiauliai      16128    4  
Panevėžys     12968    5  
...             ...  ...  
Dusetos        1278   99  
Kavarskas      1546  100  
Smalininkai       0  101  
Troškūnai      1000  102  
Panemunė          0  103  

[103 rows x 10 columns]

In [44]:
add_miestas.iloc[[x for x in range(29,39)]]

2019   2011   2001   1989   1979   1970  1959  1923  1897  nr
Miestas                                                                      
Jurbarkas       9831  11232  13797  14310  10644   6541  4422  4409  7400  30
Raseiniai       9784  11203  12541  13211  11403   8946  6200  5270  7455  31
Vilkaviškis     9621  11547  13283  13829  11836   8452  5072  7263  5788  32
Anykščiai       8632  10575  11958  12758  10325   8250  5442  3500  3900  33
Prienai         8516   9867  11353  11909   9398   7550  5423  3260  2477  34
Joniškis        8358   9899  11329  11773   9303   7488  5889  4100  4828  35
Varėna          7987   9240  10845  12291   8015   4478  2401   407  2624  36
Kelmė           7655   9150  10900  11557   9073   6934  5140  2900  3914  37
Kaišiadorys     7486   8664  10002  10964   9022   4618  3011  1929   833  38
Naujoji Akmenė  7266   9300  12345  13590  14195  10127  5400     0     0  39

In [45]:
add_miestas.drop("nr", axis=1, inplace=True)
add_miestas

2019    2011    2001    1989    1979    1970    1959    1923  \
Miestas                                                                       
Vilnius      540919  535631  542287  576747  475825  370153  236100  167400   
Kaunas       286763  315993  378650  419745  370000  305600  216850   92446   
Klaipėda     147898  162360  192954  202929  176648  140342   89500   35845   
Šiauliai     100119  109328  133883  145629  118724   92375   59700   21387   
Panevėžys     87148   99690  119749  126483  102303   74497   41100   19197   
...             ...     ...     ...     ...     ...     ...     ...     ...   
Dusetos         560     717     914    1184    1357    1600    1806    1164   
Kavarskas       528     666     809     972    1113    1191    1287    1041   
Smalininkai     446     515     653     758     805     952    1100    1741   
Troškūnai       372     451     525     672    1174    1417    1495    1252   
Panemunė        210     274     329     398     506     545     539     637   

               1897  
Miestas              
Vilnius      154532  
Kaunas        70920  
Klaipėda      20100  
Šiauliai      16128  
Panevėžys     12968  
...             ...  
Dusetos        1278  
Kavarskas      1546  
Smalininkai       0  
Troškūnai      1000  
Panemunė          0  

[103 rows x 9 columns]

In [61]:
add_miestas[add_miestas['1959']==0]

2019   2011   2001   1989  1979  1970  1959  1923  1897
Miestas                                                             
Visaginas   18185  26804  29554  32438  6212     0     0     0     0
Elektrėnai  11276  12012  14050  15871  8466  6730     0     0     0

In [65]:
add_miestas[add_miestas['1897'] > add_miestas['2019']]

2019  2011  2001  1989  1979  1970  1959  1923  1897
Miestas                                                                  
Zarasai              6140  7349  8365  8916  7250  6624  4700  3785  6359
Švenčionys           4139  4980  5684  6469  5284  4617  4006     0  6025
Kalvarija            3858  4457  5090  5701  5879  5622  4698  4529  9378
Eišiškės             3071  3416  3765  3789  3467  3481  2532  2382  3196
Šeduva               2541  2895  3400  3584  3347  3309  3253  3186  4474
Vilkija              1898  2131  2338  2629  2371  2286  1996  2068  2012
Viekšniai            1670  1938  2270  2410  2781  2748  2734  2024  2951
Kudirkos Naumiestis  1480  1732  1997  2061  2090  2486  2574  3067  4595
Žagarė               1366  1712  2312  2649  2918  3386  3800  4730  8285
Salantai             1360  1615  1942  2431  2086  2156  2321  1942  2446
Linkuva              1277  1679  1797  2025  1876  1950  2144  1851  2077
Simnas               1269  1514  1980  2313  1625  1716  1661  1549  1642
Veisiejai            1211  1430  1762  2079  1687  1450  1513  1295  1540
Jieznas              1023  1204  1476  1883  1854  1658  1803  1000  1255
Varniai               995  1140  1355  2028  2059  2027  1902     0  2834
Daugai                980  1120  1458  2790  2054  1384  1287  1153  1288
Seda                  953  1138  1309  1500  1679  1821  2133  1851  2062
Virbalis              885  1095  1351  1566  1635  1489  1429  4018  3293
Vabalninkas           875  1057  1328  1905  2205  2070  2360  1267  2333
Obeliai               847  1074  1371  1804  1648  1681  1907  1328   975
Dūkštas               765   888  1070  1193  1633  1444  1968  1076  1000
Pandėlys              752   809  1024  1167  1129  1184  1277  1000  1221
Užventis              649   833   898  1149  1229  1406  1704     0   945
Dusetos               560   717   914  1184  1357  1600  1806  1164  1278
Kavarskas             528   666   809   972  1113  1191  1287  1041  1546
Troškūnai             372   451   525   672  1174  1417  1495  1252  1000

In [70]:
add_miestas[add_miestas['2019'] > add_miestas['2011']][['2019','2011']]

2019    2011
Miestas                     
Vilnius       540919  535631
Šalčininkai     6753    6402
Baltoji Vokė    1052    1047

In [77]:
add_miestas[(add_miestas['1897'] > add_miestas['1923']) &
(add_miestas['1923'] > add_miestas['1959'])&
(add_miestas['1959'] > add_miestas['1970'])&
(add_miestas['1970'] > add_miestas['1979'])&
(add_miestas['1979'] > add_miestas['1989'])&
(add_miestas['1989'] > add_miestas['2001'])&
(add_miestas['2001'] > add_miestas['2011'])&
(add_miestas['2011'] > add_miestas['2019'])]

2019  2011  2001  1989  1979  1970  1959  1923  1897
Miestas                                                                  
Kudirkos Naumiestis  1480  1732  1997  2061  2090  2486  2574  3067  4595
Žagarė               1366  1712  2312  2649  2918  3386  3800  4730  8285

In [92]:
procents = (add_miestas['2019'] - add_miestas['1989']) / add_miestas['1989'] * 100

print(f'\
{procents.idxmax()}\t {int(procents.max())}%\n\
{procents.idxmin()}\t{int(procents.min())}%')


Neringa	 39%
Daugai	-64%


In [93]:
add_miestas.reset_index()

Miestas    2019    2011    2001    1989    1979    1970    1959  \
0        Vilnius  540919  535631  542287  576747  475825  370153  236100   
1         Kaunas  286763  315993  378650  419745  370000  305600  216850   
2       Klaipėda  147898  162360  192954  202929  176648  140342   89500   
3       Šiauliai  100119  109328  133883  145629  118724   92375   59700   
4      Panevėžys   87148   99690  119749  126483  102303   74497   41100   
..           ...     ...     ...     ...     ...     ...     ...     ...   
98       Dusetos     560     717     914    1184    1357    1600    1806   
99     Kavarskas     528     666     809     972    1113    1191    1287   
100  Smalininkai     446     515     653     758     805     952    1100   
101    Troškūnai     372     451     525     672    1174    1417    1495   
102     Panemunė     210     274     329     398     506     545     539   

       1923    1897  percent_change  
0    167400  154532       -6.212083  
1     92446   70920      -31.681616  
2     35845   20100      -27.118352  
3     21387   16128      -31.250644  
4     19197   12968      -31.099041  
..      ...     ...             ...  
98     1164    1278      -52.702703  
99     1041    1546      -45.679012  
100    1741       0      -41.160950  
101    1252    1000      -44.642857  
102     637       0      -47.236181  

[103 rows x 11 columns]

# Pandas 2



In [274]:
import pandas as pd
import numpy as np

In [275]:
top_left = pd.read_csv('top1-25-1.csv')
top_right = pd.read_csv('top1-25-2.csv')
bottom_left = pd.read_csv('top26-50-1.csv')
bottom_right = pd.read_csv('top-26-50-2.csv')

In [276]:
bott = pd.concat([bottom_left, bottom_right], axis=1)
bott

Track.Name       Artist.Name  \
0                                 If I Can't Have You      Shawn Mendes   
1                                        Dance Monkey       Tones and I   
2                                            It's You         Ali Gatie   
3                                           Con Calma      Daddy Yankee   
4                                       QUE PRETENDES          J Balvin   
5                                            Takeaway  The Chainsmokers   
6                                             7 rings     Ariana Grande   
7                                   0.958333333333333            Maluma   
8           The London (feat. J. Cole & Travis Scott)        Young Thug   
9                                   Never Really Over        Katy Perry   
10  Summer Days (feat. Macklemore & Patrick Stump ...     Martin Garrix   
11                                         Otro Trago              Sech   
12                     Antisocial (with Travis Scott)        Ed Sheeran   
13                                             Sucker    Jonas Brothers   
14  fuck, i'm lonely (with Anne-Marie) - from 13 R...              Lauv   
15                                        Higher Love              Kygo   
16                              You Need To Calm Down      Taylor Swift   
17                                            Shallow         Lady Gaga   
18                                               Talk            Khalid   
19                                         Con Altura           ROSALNA   
20                                    One Thing Right        Marshmello   
21                                           Te Robar         Nicky Jam   
22                                            Happier        Marshmello   
23                                      Call You Mine  The Chainsmokers   
24      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran   

               Genre  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
0       canadian pop               124      82            69              -4   
1     australian pop                98      59            82              -6   
2   canadian hip hop                96      46            73              -7   
3              latin                94      86            74              -3   
4              latin                93      79            64              -4   
5                edm                85      51            29              -8   
6          dance pop               140      32            78             -11   
7          reggaeton                96      71            78              -5   
8        atl hip hop                98      59            80              -7   
9          dance pop               100      88            77              -5   
10          big room               114      72            66              -7   
11    panamanian pop               176      70            75              -5   
12               pop               152      82            72              -5   
13          boy band               138      73            84              -5   
14         dance pop                95      56            81              -6   
15               edm               104      68            69              -7   
16         dance pop                85      68            77              -6   
17         dance pop                96      39            57              -6   
18               pop               136      40            90              -9   
19    r&b en espanol                98      69            88              -4   
20           brostep                88      62            66              -2   
21             latin               176      75            67              -4   
22           brostep               100      79            69              -3   
23               edm               104      70            59              -6   
24               NaN                95      79            75              -6   

    Livenes

In [277]:
top = pd.merge(top_left, top_right, on=["Track.Name", "Popularity"])
top

Track.Name    Artist.Name  \
0                                        Senorita   Shawn Mendes   
1                                           China       Anuel AA   
2                   boyfriend (with Social House)  Ariana Grande   
3                 Beautiful People (feat. Khalid)     Ed Sheeran   
4                     Goodbyes (Feat. Young Thug)    Post Malone   
5               I Don't Care (with Justin Bieber)     Ed Sheeran   
6                                          Ransom      Lil Tecca   
7                               How Do You Sleep?      Sam Smith   
8                           Old Town Road - Remix      Lil Nas X   
9                                         bad guy  Billie Eilish   
10                                       Callaita      Bad Bunny   
11          Loco Contigo (feat. J. Balvin & Tyga)       DJ Snake   
12                              Someone You Loved  Lewis Capaldi   
13                             Otro Trago - Remix           Sech   
14       Money In The Grave (Drake ft. Rick Ross)          Drake   
15                      No Guidance (feat. Drake)    Chris Brown   
16                                     LA CANCION       J Balvin   
17  Sunflower - Spider-Man: Into the Spider-Verse    Post Malone   
18                                         Lalala            Y2K   
19                                    Truth Hurts          Lizzo   
20                            Piece Of Your Heart         MEDUZA   
21                                         Panini      Lil Nas X   
22                           No Me Conoce - Remix    Jhay Cortez   
23                                Soltera - Remix          Lunay   
24                   bad guy (with Justin Bieber)  Billie Eilish   

               Genre  Popularity  Beats.Per.Minute  Energy  Danceability  \
0       canadian pop        79.0               117      55            76   
1     reggaeton flow        92.0               105      81            79   
2          dance pop        85.0               190      80            40   
3                pop         NaN                93      65            64   
4            dfw rap        94.0               150      65            58   
5                pop        84.0               102      68            80   
6         trap music        92.0               180      64            75   
7                pop        90.0               111      68            48   
8        country rap        87.0               136      62            88   
9         electropop        95.0               135      43            70   
10         reggaeton        93.0               176      62            61   
11         dance pop        86.0                96      71            82   
12               pop        88.0               110      41            50   
13    panamanian pop        87.0               176      79            73   
14  canadian hip hop        92.0               101      50            83   
15         dance pop        82.0                93      45            70   
16             latin        90.0               176      65            75   
17           dfw rap        91.0                90      48            76   
18               NaN        88.0               130      39            84   
19       escape room        91.0               158      62            72   
20         pop house        91.0               124      74            68   
21       country rap        91.0               154      59            70   
22    reggaeton flow        83.0                92      79            81   
23             latin        91.0                92      78            80   
24        electropop         NaN               135      45            67   

    Loudness..dB..  Liveness  Valence.  Length.  Acousticness..  Speechiness.  
0               -6         8        75      191               4             3  
1               -4         8        61      302               8             9  
2               -4        16        70      186      

In [278]:
both = pd.concat([top, bott])
both

Track.Name       Artist.Name  \
0                                            Senorita      Shawn Mendes   
1                                               China          Anuel AA   
2                       boyfriend (with Social House)     Ariana Grande   
3                     Beautiful People (feat. Khalid)        Ed Sheeran   
4                         Goodbyes (Feat. Young Thug)       Post Malone   
5                   I Don't Care (with Justin Bieber)        Ed Sheeran   
6                                              Ransom         Lil Tecca   
7                                   How Do You Sleep?         Sam Smith   
8                               Old Town Road - Remix         Lil Nas X   
9                                             bad guy     Billie Eilish   
10                                           Callaita         Bad Bunny   
11              Loco Contigo (feat. J. Balvin & Tyga)          DJ Snake   
12                                  Someone You Loved     Lewis Capaldi   
13                                 Otro Trago - Remix              Sech   
14           Money In The Grave (Drake ft. Rick Ross)             Drake   
15                          No Guidance (feat. Drake)       Chris Brown   
16                                         LA CANCION          J Balvin   
17      Sunflower - Spider-Man: Into the Spider-Verse       Post Malone   
18                                             Lalala               Y2K   
19                                        Truth Hurts             Lizzo   
20                                Piece Of Your Heart            MEDUZA   
21                                             Panini         Lil Nas X   
22                               No Me Conoce - Remix       Jhay Cortez   
23                                    Soltera - Remix             Lunay   
24                       bad guy (with Justin Bieber)     Billie Eilish   
0                                 If I Can't Have You      Shawn Mendes   
1                                        Dance Monkey       Tones and I   
2                                            It's You         Ali Gatie   
3                                           Con Calma      Daddy Yankee   
4                                       QUE PRETENDES          J Balvin   
5                                            Takeaway  The Chainsmokers   
6                                             7 rings     Ariana Grande   
7                                   0.958333333333333            Maluma   
8           The London (feat. J. Cole & Travis Scott)        Young Thug   
9                                   Never Really Over        Katy Perry   
10  Summer Days (feat. Macklemore & Patrick Stump ...     Martin Garrix   
11                                         Otro Trago              Sech   
12                     Antisocial (with Travis Scott)        Ed Sheeran   
13                                             Sucker    Jonas Brothers   
14  fuck, i'm lonely (with Anne-Marie) - from 13 R...              Lauv   
15                                        Higher Love              Kygo   
16                              You Need To Calm Down      Taylor Swift   
17                                            Shallow         Lady Gaga   
18                                               Talk            Khalid   
19                                         Con Altura           ROSALNA   
20                                    One Thing Right        Marshmello   
21                                           Te Robar         Nicky Jam   
22                                            Happier        Marshmello   
23                                      Call You Mine  The Chainsmokers   
24      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran   

               Genre  Popularity  Beats.Per.Minute  Energy  Danceability  \
0       canadian pop        79.0               117      55            76   
1     reggaeton flow        92.0               105      81       

In [279]:
both.index = range(1, len(both) + 1)
both

Track.Name       Artist.Name  \
1                                            Senorita      Shawn Mendes   
2                                               China          Anuel AA   
3                       boyfriend (with Social House)     Ariana Grande   
4                     Beautiful People (feat. Khalid)        Ed Sheeran   
5                         Goodbyes (Feat. Young Thug)       Post Malone   
6                   I Don't Care (with Justin Bieber)        Ed Sheeran   
7                                              Ransom         Lil Tecca   
8                                   How Do You Sleep?         Sam Smith   
9                               Old Town Road - Remix         Lil Nas X   
10                                            bad guy     Billie Eilish   
11                                           Callaita         Bad Bunny   
12              Loco Contigo (feat. J. Balvin & Tyga)          DJ Snake   
13                                  Someone You Loved     Lewis Capaldi   
14                                 Otro Trago - Remix              Sech   
15           Money In The Grave (Drake ft. Rick Ross)             Drake   
16                          No Guidance (feat. Drake)       Chris Brown   
17                                         LA CANCION          J Balvin   
18      Sunflower - Spider-Man: Into the Spider-Verse       Post Malone   
19                                             Lalala               Y2K   
20                                        Truth Hurts             Lizzo   
21                                Piece Of Your Heart            MEDUZA   
22                                             Panini         Lil Nas X   
23                               No Me Conoce - Remix       Jhay Cortez   
24                                    Soltera - Remix             Lunay   
25                       bad guy (with Justin Bieber)     Billie Eilish   
26                                If I Can't Have You      Shawn Mendes   
27                                       Dance Monkey       Tones and I   
28                                           It's You         Ali Gatie   
29                                          Con Calma      Daddy Yankee   
30                                      QUE PRETENDES          J Balvin   
31                                           Takeaway  The Chainsmokers   
32                                            7 rings     Ariana Grande   
33                                  0.958333333333333            Maluma   
34          The London (feat. J. Cole & Travis Scott)        Young Thug   
35                                  Never Really Over        Katy Perry   
36  Summer Days (feat. Macklemore & Patrick Stump ...     Martin Garrix   
37                                         Otro Trago              Sech   
38                     Antisocial (with Travis Scott)        Ed Sheeran   
39                                             Sucker    Jonas Brothers   
40  fuck, i'm lonely (with Anne-Marie) - from 13 R...              Lauv   
41                                        Higher Love              Kygo   
42                              You Need To Calm Down      Taylor Swift   
43                                            Shallow         Lady Gaga   
44                                               Talk            Khalid   
45                                         Con Altura           ROSALNA   
46                                    One Thing Right        Marshmello   
47                                           Te Robar         Nicky Jam   
48                                            Happier        Marshmello   
49                                      Call You Mine  The Chainsmokers   
50      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran   

               Genre  Popularity  Beats.Per.Minute  Energy  Danceability  \
1       canadian pop        79.0               117      55            76   
2     reggaeton flow        92.0               105      81       

In [297]:
by_genre = both.groupby("Genre")
by_genre

In [281]:
avg_popularity = both.groupby('Genre')['Popularity'].mean()

In [282]:
most_popular_genre = avg_popularity.idxmax()
most_popular_values = avg_popularity.loc[most_popular_genre]


In [283]:
least_popular_genre = avg_popularity.idxmin()
least_popular_values = avg_popularity.loc[least_popular_genre]

In [284]:
print(f'{most_popular_genre}, {most_popular_values},\n{least_popular_genre}, {least_popular_values}')

electropop, 95.0,
canadian pop, 74.5


In [329]:
indicators = both.columns.tolist()[3:]
genres = by_genre.mean().idxmax()
score = by_genre.mean().max()
result = pd.DataFrame([indicators,genres.values, score.values],["Indicators", "Genres","Score"]).transpose()
result



/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_30128/3610983848.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  genres = by_genre.mean().idxmax()
/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_30128/3610983848.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  score = by_genre.mean().max()


Indicators          Genres  Score
0        Popularity      electropop   95.0
1  Beats.Per.Minute      trap music  180.0
2            Energy  reggaeton flow   80.0
3      Danceability  r&b en espanol   88.0
4    Loudness..dB..         brostep   -2.5
5          Liveness         brostep   37.5
6          Valence.        boy band   95.0
7           Length.  reggaeton flow  305.5
8    Acousticness..  australian pop   69.0
9      Speechiness.      electropop   34.0

In [265]:
result = both[both.isnull().any(axis=1)]
result


Track.Name    Artist.Name       Genre  \
4                 Beautiful People (feat. Khalid)     Ed Sheeran         pop   
19                                         Lalala            Y2K         NaN   
25                   bad guy (with Justin Bieber)  Billie Eilish  electropop   
48                                        Happier     Marshmello     brostep   
50  Cross Me (feat. Chance the Rapper & PnB Rock)     Ed Sheeran         NaN   

    Popularity  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
4          NaN                93      65            64              -8   
19        88.0               130      39            84              -8   
25         NaN               135      45            67             -11   
48         NaN               100      79            69              -3   
50        82.0                95      79            75              -6   

    Liveness  Valence.  Length.  Acousticness..  Speechiness.  
4          8        55      198              12            19  
19        14        50      161              18             8  
25        12        68      195              25            30  
48        17        67      214              19             5  
50         7        61      206              21            12

In [269]:
result['Genre'] = result['Genre'].fillna('pop')

/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_30128/2721207130.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['Genre'] = result['Genre'].fillna('pop')


In [270]:
result

Track.Name    Artist.Name       Genre  \
4                 Beautiful People (feat. Khalid)     Ed Sheeran         pop   
19                                         Lalala            Y2K         pop   
25                   bad guy (with Justin Bieber)  Billie Eilish  electropop   
48                                        Happier     Marshmello     brostep   
50  Cross Me (feat. Chance the Rapper & PnB Rock)     Ed Sheeran         pop   

    Popularity  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
4          NaN                93      65            64              -8   
19        88.0               130      39            84              -8   
25         NaN               135      45            67             -11   
48         NaN               100      79            69              -3   
50        82.0                95      79            75              -6   

    Liveness  Valence.  Length.  Acousticness..  Speechiness.  
4          8        55      198              12            19  
19        14        50      161              18             8  
25        12        68      195              25            30  
48        17        67      214              19             5  
50         7        61      206              21            12

In [272]:
result["Popularity"] = result["Popularity"].fillna(value=result["Popularity"].mean())
result

/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_30128/116685652.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result["Popularity"] = result["Popularity"].fillna(value=result["Popularity"].mean())


Track.Name    Artist.Name       Genre  \
4                 Beautiful People (feat. Khalid)     Ed Sheeran         pop   
19                                         Lalala            Y2K         pop   
25                   bad guy (with Justin Bieber)  Billie Eilish  electropop   
48                                        Happier     Marshmello     brostep   
50  Cross Me (feat. Chance the Rapper & PnB Rock)     Ed Sheeran         pop   

    Popularity  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
4         85.0                93      65            64              -8   
19        88.0               130      39            84              -8   
25        85.0               135      45            67             -11   
48        85.0               100      79            69              -3   
50        82.0                95      79            75              -6   

    Liveness  Valence.  Length.  Acousticness..  Speechiness.  
4          8        55      198              12            19  
19        14        50      161              18             8  
25        12        68      195              25            30  
48        17        67      214              19             5  
50         7        61      206              21            12