# Iterator/Generator


In [2]:
def poriniai(iki):
    count = 2
    while count <= iki:
        yield count
        count += 2


In [3]:
skaiciuojam = poriniai(99)

In [4]:
print(next(skaiciuojam))

2


In [5]:
for skaicius in skaiciuojam:
    print(skaicius)

4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [6]:
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b
        

In [7]:
ats = fib(45)
print(list(ats))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578, 5702887, 9227465, 14930352, 24157817, 39088169, 63245986, 102334155, 165580141, 267914296, 433494437, 701408733]


In [8]:
kodas = "1149"
def lauziam_koda():
    skaicius = 0
    while skaicius < 10000:
        spejimas = f'{skaicius:04}'
        if spejimas == kodas:
            print(f'{spejimas} yra tai, ko jus ieskote')
            break
        yield spejimas
        skaicius += 1


In [9]:
bandom = lauziam_koda()
while True:
    try:
        print(next(bandom))
    except StopIteration:
        break

0000
0001
0002
0003
0004
0005
0006
0007
0008
0009
0010
0011
0012
0013
0014
0015
0016
0017
0018
0019
0020
0021
0022
0023
0024
0025
0026
0027
0028
0029
0030
0031
0032
0033
0034
0035
0036
0037
0038
0039
0040
0041
0042
0043
0044
0045
0046
0047
0048
0049
0050
0051
0052
0053
0054
0055
0056
0057
0058
0059
0060
0061
0062
0063
0064
0065
0066
0067
0068
0069
0070
0071
0072
0073
0074
0075
0076
0077
0078
0079
0080
0081
0082
0083
0084
0085
0086
0087
0088
0089
0090
0091
0092
0093
0094
0095
0096
0097
0098
0099
0100
0101
0102
0103
0104
0105
0106
0107
0108
0109
0110
0111
0112
0113
0114
0115
0116
0117
0118
0119
0120
0121
0122
0123
0124
0125
0126
0127
0128
0129
0130
0131
0132
0133
0134
0135
0136
0137
0138
0139
0140
0141
0142
0143
0144
0145
0146
0147
0148
0149
0150
0151
0152
0153
0154
0155
0156
0157
0158
0159
0160
0161
0162
0163
0164
0165
0166
0167
0168
0169
0170
0171
0172
0173
0174
0175
0176
0177
0178
0179
0180
0181
0182
0183
0184
0185
0186
0187
0188
0189
0190
0191
0192
0193
0194
0195
0196
0197
0198
0199


In [10]:
def ieskom():
    with open("gen_failui/generatoriui.txt", "r") as failas:
        while True:
            for eilute in failas:
                yield eilute[:-1]


# DEKORATORIAI



In [11]:
def stri_decorator(fn):
    def wrapper(*args, **kwargs):
        for a in args:
            if type(a) != str:
                return "text must be a string"
        return fn(*args, **kwargs)
    return wrapper

In [12]:
@stri_decorator
def return_string(*args):
    return args


In [13]:
return_string("")

('',)

In [14]:
def less_than_two(fn):
    def wrapper(*args, **kwargs):
        if len(args) > 2:
            return "Enter less than 2 parameters"
        return fn(*args)
    return wrapper

In [15]:
@stri_decorator
@less_than_two
def any_function(*args):
    return args

In [16]:
any_function("stringas", "stringiukas")

('stringas', 'stringiukas')

In [17]:
from time import sleep
from functools import wraps

def delay(seconds):
    def delay(fn):
        @wraps(fn)
        def wrapper(*args, **kwargs):
            print(f"function will be delayed for {seconds} seconds. ")
            sleep(seconds)
            return fn(*args, **kwargs)
        return wrapper
    return delay

In [18]:
@delay(2.5)
@stri_decorator
@less_than_two
def any_function(*args):
    return args

In [19]:
any_function("stringas", "stringiukas")

function will be delayed for 2.5 seconds. 


('stringas', 'stringiukas')

### how long does it takes 

In [20]:
from time import time
def performance(fn):
    def wrapper(*args, **kwargs):
        t1 = time()
        result = fn(*args, **kwargs)
        t2 = time()
        diff = t2 - t1
        # print(f"It took {diff}")
        return result, diff
    return wrapper

In [21]:
import requests  # importuojame requests
from time import time  # importuojame time modulį

start_time = time()  # fiksuojame starto laiką
r = requests.get('http://www.cnn.com')  # sukuriame http užklausą
print(r.status_code)  # spausdiname status code (200 = OK, 404 = Not Found, ir t.t. galima pasiguglinti http status codes)
end_time = time()  # fiksuojame pabaigos laiką
print(end_time - start_time)  # atspausdiname laiką, per kurį gaovme atsakymą

200
2.0371038913726807


# NUMPY

In [22]:
import numpy as np

In [23]:
pirmas = np.arange(1,10)
print(pirmas)

[1 2 3 4 5 6 7 8 9]


In [24]:
antras = np.zeros(10)
print(antras)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
trecias = np.ones(10)
trecias

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
ketvirtas = np.ones(10) + 3
ketvirtas

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [27]:
penktas = np.arange(0,102,2)
penktas

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [28]:
change[2,1]

NameError: name 'change' is not defined

In [ ]:
change[-1:]

array([[21, 22, 23, 24, 25]])

In [ ]:
change[0:3, 0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
sixth = np.arange(1,26)
change = sixth.reshape(5,5)
change

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
change[1:-1, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [ ]:
change[-2:, 0:-2]

array([[16, 17, 18],
       [21, 22, 23]])

In [ ]:
trolo = np.random.rand(20)

array([0.08593991, 0.3127147 , 0.31026176, 0.32462699, 0.5040098 ,
       0.07136543, 0.01249324, 0.60335239, 0.73221385, 0.45417201,
       0.07741429, 0.51548049, 0.48712068, 0.35992055, 0.04469814,
       0.54129841, 0.82772673, 0.54359662, 0.37453503, 0.3293201 ])

In [ ]:
print(trolo.max(), trolo.argmax())

0.8277267336478586 16


In [ ]:
print(trolo.min(), trolo.argmin())

0.012493244105172163 6


In [ ]:
trolo.dtype

dtype('float64')

In [ ]:
more = np.arange(1,101)
more

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
more[more>90]


array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
more[more % 7 == 0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [ ]:
np.linspace(0.025,1,40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [ ]:
traukiasi = np.arange(2,1001)
traukiasi

In [ ]:
bandomd=traukiasi[(traukiasi ** 0.5) % 1==0].reshape(5,6)
bandomd

array([[  4,   9,  16,  25,  36,  49],
       [ 64,  81, 100, 121, 144, 169],
       [196, 225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576, 625],
       [676, 729, 784, 841, 900, 961]])

# PANDAS 1



In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df = pd.read_csv('miestai_isvalyti.csv')
df

Miestas    2019    2011    2001    1989    1979    1970    1959  \
0        Vilnius  540919  535631  542287  576747  475825  370153  236100   
1         Kaunas  286763  315993  378650  419745  370000  305600  216850   
2       Klaipėda  147898  162360  192954  202929  176648  140342   89500   
3       Šiauliai  100119  109328  133883  145629  118724   92375   59700   
4      Panevėžys   87148   99690  119749  126483  102303   74497   41100   
..           ...     ...     ...     ...     ...     ...     ...     ...   
98       Dusetos     560     717     914    1184    1357    1600    1806   
99     Kavarskas     528     666     809     972    1113    1191    1287   
100  Smalininkai     446     515     653     758     805     952    1100   
101    Troškūnai     372     451     525     672    1174    1417    1495   
102     Panemunė     210     274     329     398     506     545     539   

       1923    1897  
0    167400  154532  
1     92446   70920  
2     35845   20100  
3     21387   16128  
4     19197   12968  
..      ...     ...  
98     1164    1278  
99     1041    1546  
100    1741       0  
101    1252    1000  
102     637       0  

[103 rows x 10 columns]

In [ ]:
add_miestas = df.set_index("Miestas")
add_miestas

2019    2011    2001    1989    1979    1970    1959    1923  \
Miestas                                                                       
Vilnius      540919  535631  542287  576747  475825  370153  236100  167400   
Kaunas       286763  315993  378650  419745  370000  305600  216850   92446   
Klaipėda     147898  162360  192954  202929  176648  140342   89500   35845   
Šiauliai     100119  109328  133883  145629  118724   92375   59700   21387   
Panevėžys     87148   99690  119749  126483  102303   74497   41100   19197   
...             ...     ...     ...     ...     ...     ...     ...     ...   
Dusetos         560     717     914    1184    1357    1600    1806    1164   
Kavarskas       528     666     809     972    1113    1191    1287    1041   
Smalininkai     446     515     653     758     805     952    1100    1741   
Troškūnai       372     451     525     672    1174    1417    1495    1252   
Panemunė        210     274     329     398     506     545     539     637   

               1897  
Miestas              
Vilnius      154532  
Kaunas        70920  
Klaipėda      20100  
Šiauliai      16128  
Panevėžys     12968  
...             ...  
Dusetos        1278  
Kavarskas      1546  
Smalininkai       0  
Troškūnai      1000  
Panemunė          0  

[103 rows x 9 columns]

In [ ]:
add_miestas.shape

(103, 9)

In [ ]:
naujas = range(1,104)
add_miestas["nr"] = naujas
add_miestas

2019    2011    2001    1989    1979    1970    1959    1923  \
Miestas                                                                       
Vilnius      540919  535631  542287  576747  475825  370153  236100  167400   
Kaunas       286763  315993  378650  419745  370000  305600  216850   92446   
Klaipėda     147898  162360  192954  202929  176648  140342   89500   35845   
Šiauliai     100119  109328  133883  145629  118724   92375   59700   21387   
Panevėžys     87148   99690  119749  126483  102303   74497   41100   19197   
...             ...     ...     ...     ...     ...     ...     ...     ...   
Dusetos         560     717     914    1184    1357    1600    1806    1164   
Kavarskas       528     666     809     972    1113    1191    1287    1041   
Smalininkai     446     515     653     758     805     952    1100    1741   
Troškūnai       372     451     525     672    1174    1417    1495    1252   
Panemunė        210     274     329     398     506     545     539     637   

               1897   nr  
Miestas                   
Vilnius      154532    1  
Kaunas        70920    2  
Klaipėda      20100    3  
Šiauliai      16128    4  
Panevėžys     12968    5  
...             ...  ...  
Dusetos        1278   99  
Kavarskas      1546  100  
Smalininkai       0  101  
Troškūnai      1000  102  
Panemunė          0  103  

[103 rows x 10 columns]

In [ ]:
add_miestas.iloc[[x for x in range(29,39)]]

2019   2011   2001   1989   1979   1970  1959  1923  1897  nr
Miestas                                                                      
Jurbarkas       9831  11232  13797  14310  10644   6541  4422  4409  7400  30
Raseiniai       9784  11203  12541  13211  11403   8946  6200  5270  7455  31
Vilkaviškis     9621  11547  13283  13829  11836   8452  5072  7263  5788  32
Anykščiai       8632  10575  11958  12758  10325   8250  5442  3500  3900  33
Prienai         8516   9867  11353  11909   9398   7550  5423  3260  2477  34
Joniškis        8358   9899  11329  11773   9303   7488  5889  4100  4828  35
Varėna          7987   9240  10845  12291   8015   4478  2401   407  2624  36
Kelmė           7655   9150  10900  11557   9073   6934  5140  2900  3914  37
Kaišiadorys     7486   8664  10002  10964   9022   4618  3011  1929   833  38
Naujoji Akmenė  7266   9300  12345  13590  14195  10127  5400     0     0  39

In [ ]:
add_miestas.drop("nr", axis=1, inplace=True)
add_miestas

2019    2011    2001    1989    1979    1970    1959    1923  \
Miestas                                                                       
Vilnius      540919  535631  542287  576747  475825  370153  236100  167400   
Kaunas       286763  315993  378650  419745  370000  305600  216850   92446   
Klaipėda     147898  162360  192954  202929  176648  140342   89500   35845   
Šiauliai     100119  109328  133883  145629  118724   92375   59700   21387   
Panevėžys     87148   99690  119749  126483  102303   74497   41100   19197   
...             ...     ...     ...     ...     ...     ...     ...     ...   
Dusetos         560     717     914    1184    1357    1600    1806    1164   
Kavarskas       528     666     809     972    1113    1191    1287    1041   
Smalininkai     446     515     653     758     805     952    1100    1741   
Troškūnai       372     451     525     672    1174    1417    1495    1252   
Panemunė        210     274     329     398     506     545     539     637   

               1897  
Miestas              
Vilnius      154532  
Kaunas        70920  
Klaipėda      20100  
Šiauliai      16128  
Panevėžys     12968  
...             ...  
Dusetos        1278  
Kavarskas      1546  
Smalininkai       0  
Troškūnai      1000  
Panemunė          0  

[103 rows x 9 columns]

In [ ]:
add_miestas[add_miestas['1959']==0]

2019   2011   2001   1989  1979  1970  1959  1923  1897
Miestas                                                             
Visaginas   18185  26804  29554  32438  6212     0     0     0     0
Elektrėnai  11276  12012  14050  15871  8466  6730     0     0     0

In [ ]:
add_miestas[add_miestas['1897'] > add_miestas['2019']]

2019  2011  2001  1989  1979  1970  1959  1923  1897
Miestas                                                                  
Zarasai              6140  7349  8365  8916  7250  6624  4700  3785  6359
Švenčionys           4139  4980  5684  6469  5284  4617  4006     0  6025
Kalvarija            3858  4457  5090  5701  5879  5622  4698  4529  9378
Eišiškės             3071  3416  3765  3789  3467  3481  2532  2382  3196
Šeduva               2541  2895  3400  3584  3347  3309  3253  3186  4474
Vilkija              1898  2131  2338  2629  2371  2286  1996  2068  2012
Viekšniai            1670  1938  2270  2410  2781  2748  2734  2024  2951
Kudirkos Naumiestis  1480  1732  1997  2061  2090  2486  2574  3067  4595
Žagarė               1366  1712  2312  2649  2918  3386  3800  4730  8285
Salantai             1360  1615  1942  2431  2086  2156  2321  1942  2446
Linkuva              1277  1679  1797  2025  1876  1950  2144  1851  2077
Simnas               1269  1514  1980  2313  1625  1716  1661  1549  1642
Veisiejai            1211  1430  1762  2079  1687  1450  1513  1295  1540
Jieznas              1023  1204  1476  1883  1854  1658  1803  1000  1255
Varniai               995  1140  1355  2028  2059  2027  1902     0  2834
Daugai                980  1120  1458  2790  2054  1384  1287  1153  1288
Seda                  953  1138  1309  1500  1679  1821  2133  1851  2062
Virbalis              885  1095  1351  1566  1635  1489  1429  4018  3293
Vabalninkas           875  1057  1328  1905  2205  2070  2360  1267  2333
Obeliai               847  1074  1371  1804  1648  1681  1907  1328   975
Dūkštas               765   888  1070  1193  1633  1444  1968  1076  1000
Pandėlys              752   809  1024  1167  1129  1184  1277  1000  1221
Užventis              649   833   898  1149  1229  1406  1704     0   945
Dusetos               560   717   914  1184  1357  1600  1806  1164  1278
Kavarskas             528   666   809   972  1113  1191  1287  1041  1546
Troškūnai             372   451   525   672  1174  1417  1495  1252  1000

In [ ]:
add_miestas[add_miestas['2019'] > add_miestas['2011']][['2019','2011']]

2019    2011
Miestas                     
Vilnius       540919  535631
Šalčininkai     6753    6402
Baltoji Vokė    1052    1047

In [ ]:
add_miestas[(add_miestas['1897'] > add_miestas['1923']) &
(add_miestas['1923'] > add_miestas['1959'])&
(add_miestas['1959'] > add_miestas['1970'])&
(add_miestas['1970'] > add_miestas['1979'])&
(add_miestas['1979'] > add_miestas['1989'])&
(add_miestas['1989'] > add_miestas['2001'])&
(add_miestas['2001'] > add_miestas['2011'])&
(add_miestas['2011'] > add_miestas['2019'])]

2019  2011  2001  1989  1979  1970  1959  1923  1897
Miestas                                                                  
Kudirkos Naumiestis  1480  1732  1997  2061  2090  2486  2574  3067  4595
Žagarė               1366  1712  2312  2649  2918  3386  3800  4730  8285

In [ ]:
procents = (add_miestas['2019'] - add_miestas['1989']) / add_miestas['1989'] * 100

print(f'\
{procents.idxmax()}\t {int(procents.max())}%\n\
{procents.idxmin()}\t{int(procents.min())}%')


Neringa	 39%
Daugai	-64%


In [ ]:
add_miestas.reset_index()

Miestas    2019    2011    2001    1989    1979    1970    1959  \
0        Vilnius  540919  535631  542287  576747  475825  370153  236100   
1         Kaunas  286763  315993  378650  419745  370000  305600  216850   
2       Klaipėda  147898  162360  192954  202929  176648  140342   89500   
3       Šiauliai  100119  109328  133883  145629  118724   92375   59700   
4      Panevėžys   87148   99690  119749  126483  102303   74497   41100   
..           ...     ...     ...     ...     ...     ...     ...     ...   
98       Dusetos     560     717     914    1184    1357    1600    1806   
99     Kavarskas     528     666     809     972    1113    1191    1287   
100  Smalininkai     446     515     653     758     805     952    1100   
101    Troškūnai     372     451     525     672    1174    1417    1495   
102     Panemunė     210     274     329     398     506     545     539   

       1923    1897  percent_change  
0    167400  154532       -6.212083  
1     92446   70920      -31.681616  
2     35845   20100      -27.118352  
3     21387   16128      -31.250644  
4     19197   12968      -31.099041  
..      ...     ...             ...  
98     1164    1278      -52.702703  
99     1041    1546      -45.679012  
100    1741       0      -41.160950  
101    1252    1000      -44.642857  
102     637       0      -47.236181  

[103 rows x 11 columns]

# Pandas 2



In [ ]:
import pandas as pd
import numpy as np

In [ ]:
top_left = pd.read_csv('top1-25-1.csv')
top_right = pd.read_csv('top1-25-2.csv')
bottom_left = pd.read_csv('top26-50-1.csv')
bottom_right = pd.read_csv('top-26-50-2.csv')

In [ ]:
bott = pd.concat([bottom_left, bottom_right], axis=1)
bott

Track.Name       Artist.Name  \
0                                 If I Can't Have You      Shawn Mendes   
1                                        Dance Monkey       Tones and I   
2                                            It's You         Ali Gatie   
3                                           Con Calma      Daddy Yankee   
4                                       QUE PRETENDES          J Balvin   
5                                            Takeaway  The Chainsmokers   
6                                             7 rings     Ariana Grande   
7                                   0.958333333333333            Maluma   
8           The London (feat. J. Cole & Travis Scott)        Young Thug   
9                                   Never Really Over        Katy Perry   
10  Summer Days (feat. Macklemore & Patrick Stump ...     Martin Garrix   
11                                         Otro Trago              Sech   
12                     Antisocial (with Travis Scott)        Ed Sheeran   
13                                             Sucker    Jonas Brothers   
14  fuck, i'm lonely (with Anne-Marie) - from 13 R...              Lauv   
15                                        Higher Love              Kygo   
16                              You Need To Calm Down      Taylor Swift   
17                                            Shallow         Lady Gaga   
18                                               Talk            Khalid   
19                                         Con Altura           ROSALNA   
20                                    One Thing Right        Marshmello   
21                                           Te Robar         Nicky Jam   
22                                            Happier        Marshmello   
23                                      Call You Mine  The Chainsmokers   
24      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran   

               Genre  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
0       canadian pop               124      82            69              -4   
1     australian pop                98      59            82              -6   
2   canadian hip hop                96      46            73              -7   
3              latin                94      86            74              -3   
4              latin                93      79            64              -4   
5                edm                85      51            29              -8   
6          dance pop               140      32            78             -11   
7          reggaeton                96      71            78              -5   
8        atl hip hop                98      59            80              -7   
9          dance pop               100      88            77              -5   
10          big room               114      72            66              -7   
11    panamanian pop               176      70            75              -5   
12               pop               152      82            72              -5   
13          boy band               138      73            84              -5   
14         dance pop                95      56            81              -6   
15               edm               104      68            69              -7   
16         dance pop                85      68            77              -6   
17         dance pop                96      39            57              -6   
18               pop               136      40            90              -9   
19    r&b en espanol                98      69            88              -4   
20           brostep                88      62            66              -2   
21             latin               176      75            67              -4   
22           brostep               100      79            69              -3   
23               edm               104      70            59              -6   
24               NaN                95      79            75              -6   

    Livenes

In [ ]:
top = pd.merge(top_left, top_right, on=["Track.Name", "Popularity"])
top

Track.Name    Artist.Name  \
0                                        Senorita   Shawn Mendes   
1                                           China       Anuel AA   
2                   boyfriend (with Social House)  Ariana Grande   
3                 Beautiful People (feat. Khalid)     Ed Sheeran   
4                     Goodbyes (Feat. Young Thug)    Post Malone   
5               I Don't Care (with Justin Bieber)     Ed Sheeran   
6                                          Ransom      Lil Tecca   
7                               How Do You Sleep?      Sam Smith   
8                           Old Town Road - Remix      Lil Nas X   
9                                         bad guy  Billie Eilish   
10                                       Callaita      Bad Bunny   
11          Loco Contigo (feat. J. Balvin & Tyga)       DJ Snake   
12                              Someone You Loved  Lewis Capaldi   
13                             Otro Trago - Remix           Sech   
14       Money In The Grave (Drake ft. Rick Ross)          Drake   
15                      No Guidance (feat. Drake)    Chris Brown   
16                                     LA CANCION       J Balvin   
17  Sunflower - Spider-Man: Into the Spider-Verse    Post Malone   
18                                         Lalala            Y2K   
19                                    Truth Hurts          Lizzo   
20                            Piece Of Your Heart         MEDUZA   
21                                         Panini      Lil Nas X   
22                           No Me Conoce - Remix    Jhay Cortez   
23                                Soltera - Remix          Lunay   
24                   bad guy (with Justin Bieber)  Billie Eilish   

               Genre  Popularity  Beats.Per.Minute  Energy  Danceability  \
0       canadian pop        79.0               117      55            76   
1     reggaeton flow        92.0               105      81            79   
2          dance pop        85.0               190      80            40   
3                pop         NaN                93      65            64   
4            dfw rap        94.0               150      65            58   
5                pop        84.0               102      68            80   
6         trap music        92.0               180      64            75   
7                pop        90.0               111      68            48   
8        country rap        87.0               136      62            88   
9         electropop        95.0               135      43            70   
10         reggaeton        93.0               176      62            61   
11         dance pop        86.0                96      71            82   
12               pop        88.0               110      41            50   
13    panamanian pop        87.0               176      79            73   
14  canadian hip hop        92.0               101      50            83   
15         dance pop        82.0                93      45            70   
16             latin        90.0               176      65            75   
17           dfw rap        91.0                90      48            76   
18               NaN        88.0               130      39            84   
19       escape room        91.0               158      62            72   
20         pop house        91.0               124      74            68   
21       country rap        91.0               154      59            70   
22    reggaeton flow        83.0                92      79            81   
23             latin        91.0                92      78            80   
24        electropop         NaN               135      45            67   

    Loudness..dB..  Liveness  Valence.  Length.  Acousticness..  Speechiness.  
0               -6         8        75      191               4             3  
1               -4         8        61      302               8             9  
2               -4        16        70      186      

In [ ]:
both = pd.concat([top, bott])
both

Track.Name       Artist.Name  \
0                                            Senorita      Shawn Mendes   
1                                               China          Anuel AA   
2                       boyfriend (with Social House)     Ariana Grande   
3                     Beautiful People (feat. Khalid)        Ed Sheeran   
4                         Goodbyes (Feat. Young Thug)       Post Malone   
5                   I Don't Care (with Justin Bieber)        Ed Sheeran   
6                                              Ransom         Lil Tecca   
7                                   How Do You Sleep?         Sam Smith   
8                               Old Town Road - Remix         Lil Nas X   
9                                             bad guy     Billie Eilish   
10                                           Callaita         Bad Bunny   
11              Loco Contigo (feat. J. Balvin & Tyga)          DJ Snake   
12                                  Someone You Loved     Lewis Capaldi   
13                                 Otro Trago - Remix              Sech   
14           Money In The Grave (Drake ft. Rick Ross)             Drake   
15                          No Guidance (feat. Drake)       Chris Brown   
16                                         LA CANCION          J Balvin   
17      Sunflower - Spider-Man: Into the Spider-Verse       Post Malone   
18                                             Lalala               Y2K   
19                                        Truth Hurts             Lizzo   
20                                Piece Of Your Heart            MEDUZA   
21                                             Panini         Lil Nas X   
22                               No Me Conoce - Remix       Jhay Cortez   
23                                    Soltera - Remix             Lunay   
24                       bad guy (with Justin Bieber)     Billie Eilish   
0                                 If I Can't Have You      Shawn Mendes   
1                                        Dance Monkey       Tones and I   
2                                            It's You         Ali Gatie   
3                                           Con Calma      Daddy Yankee   
4                                       QUE PRETENDES          J Balvin   
5                                            Takeaway  The Chainsmokers   
6                                             7 rings     Ariana Grande   
7                                   0.958333333333333            Maluma   
8           The London (feat. J. Cole & Travis Scott)        Young Thug   
9                                   Never Really Over        Katy Perry   
10  Summer Days (feat. Macklemore & Patrick Stump ...     Martin Garrix   
11                                         Otro Trago              Sech   
12                     Antisocial (with Travis Scott)        Ed Sheeran   
13                                             Sucker    Jonas Brothers   
14  fuck, i'm lonely (with Anne-Marie) - from 13 R...              Lauv   
15                                        Higher Love              Kygo   
16                              You Need To Calm Down      Taylor Swift   
17                                            Shallow         Lady Gaga   
18                                               Talk            Khalid   
19                                         Con Altura           ROSALNA   
20                                    One Thing Right        Marshmello   
21                                           Te Robar         Nicky Jam   
22                                            Happier        Marshmello   
23                                      Call You Mine  The Chainsmokers   
24      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran   

               Genre  Popularity  Beats.Per.Minute  Energy  Danceability  \
0       canadian pop        79.0               117      55            76   
1     reggaeton flow        92.0               105      81       

In [ ]:
both.index = range(1, len(both) + 1)
both

Track.Name       Artist.Name  \
1                                            Senorita      Shawn Mendes   
2                                               China          Anuel AA   
3                       boyfriend (with Social House)     Ariana Grande   
4                     Beautiful People (feat. Khalid)        Ed Sheeran   
5                         Goodbyes (Feat. Young Thug)       Post Malone   
6                   I Don't Care (with Justin Bieber)        Ed Sheeran   
7                                              Ransom         Lil Tecca   
8                                   How Do You Sleep?         Sam Smith   
9                               Old Town Road - Remix         Lil Nas X   
10                                            bad guy     Billie Eilish   
11                                           Callaita         Bad Bunny   
12              Loco Contigo (feat. J. Balvin & Tyga)          DJ Snake   
13                                  Someone You Loved     Lewis Capaldi   
14                                 Otro Trago - Remix              Sech   
15           Money In The Grave (Drake ft. Rick Ross)             Drake   
16                          No Guidance (feat. Drake)       Chris Brown   
17                                         LA CANCION          J Balvin   
18      Sunflower - Spider-Man: Into the Spider-Verse       Post Malone   
19                                             Lalala               Y2K   
20                                        Truth Hurts             Lizzo   
21                                Piece Of Your Heart            MEDUZA   
22                                             Panini         Lil Nas X   
23                               No Me Conoce - Remix       Jhay Cortez   
24                                    Soltera - Remix             Lunay   
25                       bad guy (with Justin Bieber)     Billie Eilish   
26                                If I Can't Have You      Shawn Mendes   
27                                       Dance Monkey       Tones and I   
28                                           It's You         Ali Gatie   
29                                          Con Calma      Daddy Yankee   
30                                      QUE PRETENDES          J Balvin   
31                                           Takeaway  The Chainsmokers   
32                                            7 rings     Ariana Grande   
33                                  0.958333333333333            Maluma   
34          The London (feat. J. Cole & Travis Scott)        Young Thug   
35                                  Never Really Over        Katy Perry   
36  Summer Days (feat. Macklemore & Patrick Stump ...     Martin Garrix   
37                                         Otro Trago              Sech   
38                     Antisocial (with Travis Scott)        Ed Sheeran   
39                                             Sucker    Jonas Brothers   
40  fuck, i'm lonely (with Anne-Marie) - from 13 R...              Lauv   
41                                        Higher Love              Kygo   
42                              You Need To Calm Down      Taylor Swift   
43                                            Shallow         Lady Gaga   
44                                               Talk            Khalid   
45                                         Con Altura           ROSALNA   
46                                    One Thing Right        Marshmello   
47                                           Te Robar         Nicky Jam   
48                                            Happier        Marshmello   
49                                      Call You Mine  The Chainsmokers   
50      Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran   

               Genre  Popularity  Beats.Per.Minute  Energy  Danceability  \
1       canadian pop        79.0               117      55            76   
2     reggaeton flow        92.0               105      81       

In [ ]:
by_genre = both.groupby("Genre")
by_genre

In [ ]:
avg_popularity = both.groupby('Genre')['Popularity'].mean()

In [ ]:
most_popular_genre = avg_popularity.idxmax()
most_popular_values = avg_popularity.loc[most_popular_genre]


In [ ]:
least_popular_genre = avg_popularity.idxmin()
least_popular_values = avg_popularity.loc[least_popular_genre]

In [ ]:
print(f'{most_popular_genre}, {most_popular_values},\n{least_popular_genre}, {least_popular_values}')

electropop, 95.0,
canadian pop, 74.5


In [ ]:
indicators = both.columns.tolist()[3:]
genres = by_genre.mean().idxmax()
score = by_genre.mean().max()
result = pd.DataFrame([indicators,genres.values, score.values],["Indicators", "Genres","Score"]).transpose()
result



/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_30128/3610983848.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  genres = by_genre.mean().idxmax()
/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_30128/3610983848.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  score = by_genre.mean().max()


Indicators          Genres  Score
0        Popularity      electropop   95.0
1  Beats.Per.Minute      trap music  180.0
2            Energy  reggaeton flow   80.0
3      Danceability  r&b en espanol   88.0
4    Loudness..dB..         brostep   -2.5
5          Liveness         brostep   37.5
6          Valence.        boy band   95.0
7           Length.  reggaeton flow  305.5
8    Acousticness..  australian pop   69.0
9      Speechiness.      electropop   34.0

In [ ]:
result = both[both.isnull().any(axis=1)]
result


Track.Name    Artist.Name       Genre  \
4                 Beautiful People (feat. Khalid)     Ed Sheeran         pop   
19                                         Lalala            Y2K         NaN   
25                   bad guy (with Justin Bieber)  Billie Eilish  electropop   
48                                        Happier     Marshmello     brostep   
50  Cross Me (feat. Chance the Rapper & PnB Rock)     Ed Sheeran         NaN   

    Popularity  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
4          NaN                93      65            64              -8   
19        88.0               130      39            84              -8   
25         NaN               135      45            67             -11   
48         NaN               100      79            69              -3   
50        82.0                95      79            75              -6   

    Liveness  Valence.  Length.  Acousticness..  Speechiness.  
4          8        55      198              12            19  
19        14        50      161              18             8  
25        12        68      195              25            30  
48        17        67      214              19             5  
50         7        61      206              21            12

In [ ]:
result['Genre'] = result['Genre'].fillna('pop')

/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_30128/2721207130.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result['Genre'] = result['Genre'].fillna('pop')


In [ ]:
result

Track.Name    Artist.Name       Genre  \
4                 Beautiful People (feat. Khalid)     Ed Sheeran         pop   
19                                         Lalala            Y2K         pop   
25                   bad guy (with Justin Bieber)  Billie Eilish  electropop   
48                                        Happier     Marshmello     brostep   
50  Cross Me (feat. Chance the Rapper & PnB Rock)     Ed Sheeran         pop   

    Popularity  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
4          NaN                93      65            64              -8   
19        88.0               130      39            84              -8   
25         NaN               135      45            67             -11   
48         NaN               100      79            69              -3   
50        82.0                95      79            75              -6   

    Liveness  Valence.  Length.  Acousticness..  Speechiness.  
4          8        55      198              12            19  
19        14        50      161              18             8  
25        12        68      195              25            30  
48        17        67      214              19             5  
50         7        61      206              21            12

In [ ]:
result["Popularity"] = result["Popularity"].fillna(value=result["Popularity"].mean())
result

/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_30128/116685652.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result["Popularity"] = result["Popularity"].fillna(value=result["Popularity"].mean())


Track.Name    Artist.Name       Genre  \
4                 Beautiful People (feat. Khalid)     Ed Sheeran         pop   
19                                         Lalala            Y2K         pop   
25                   bad guy (with Justin Bieber)  Billie Eilish  electropop   
48                                        Happier     Marshmello     brostep   
50  Cross Me (feat. Chance the Rapper & PnB Rock)     Ed Sheeran         pop   

    Popularity  Beats.Per.Minute  Energy  Danceability  Loudness..dB..  \
4         85.0                93      65            64              -8   
19        88.0               130      39            84              -8   
25        85.0               135      45            67             -11   
48        85.0               100      79            69              -3   
50        82.0                95      79            75              -6   

    Liveness  Valence.  Length.  Acousticness..  Speechiness.  
4          8        55      198              12            19  
19        14        50      161              18             8  
25        12        68      195              25            30  
48        17        67      214              19             5  
50         7        61      206              21            12

# Pandas 3

In [1]:
import pandas as pd
import numpy as np
duomenys = pd.read_html('https://work.studentnews.eu/s/3695/75547-European-countries-the-table-language-population-capital-currency-phone-code-internet-code.htm')
duomenys

[         0                                                  1
 0  Country  any Austria Belgium Bulgaria Croatia Cyprus Cz...
 1      NaN                                                NaN,
              Staat                     Official languages    Population  \
 0          Austria                                 German   8.4 million   
 1          Belgium  Dutch (north), French (south), German    11 million   
 2         Bulgaria                              Bulgarian     7 million   
 3          Croatia                               Croatian   4.3 million   
 4           Cyprus                         Greek, Turkish       800 000   
 5   Czech Republic                                  Czech    10 million   
 6          Denmark                                 Danish   5.6 million   
 7          Estonia                               Estonian   1.3 million   
 8          Finland                       Finnish, Swedish   5.4 million   
 9           France                               

In [81]:
kazkas = duomenys[1]

In [26]:
kazkas.to_csv('countries.csv', index=False)

In [4]:
kazkas.to_excel('countries_xls.xls', sheet_name = 'Sheet1')

/var/folders/dp/pnrbnfys52z5ydm9h3nrkn640000gn/T/ipykernel_43688/3347375748.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  kazkas.to_excel('countries_xls.xls', sheet_name = 'Sheet1')


In [27]:
from sqlalchemy import create_engine
import sql
engine = create_engine('sqlite:///duomenys.db')

In [28]:
kazkas.to_sql('countries', engine, index=True)


32

In [32]:
connection = engine.connect()
parodom = pd.read_sql('countries', con=connection)
parodom

index           Staat                     Official languages  \
0       0         Austria                                 German   
1       1         Belgium  Dutch (north), French (south), German   
2       2        Bulgaria                              Bulgarian   
3       3         Croatia                               Croatian   
4       4          Cyprus                         Greek, Turkish   
5       5  Czech Republic                                  Czech   
6       6         Denmark                                 Danish   
7       7         Estonia                               Estonian   
8       8         Finland                       Finnish, Swedish   
9       9          France                                 French   
10     10         Germany                                 German   
11     11          Greece                                  Greek   
12     12         Hungary                              Hungarian   
13     13         Iceland                              Icelandic   
14     14         Ireland                         English, Irish   
15     15           Italy                                Italian   
16     16          Latvia                                Latvian   
17     17    Lichtenstein                                 German   
18     18       Lithuania                             Lithuanian   
19     19      Luxembourg          French, German, Luxembourgish   
20     20           Malta                       English, Maltese   
21     21     Netherlands                                  Dutch   
22     22          Norway                              Norwegian   
23     23          Poland                                 Polish   
24     24        Portugal                             Portuguese   
25     25         Romania                               Romanian   
26     26        Slovakia                              Slovakian   
27     27        Slovenia                              Slovenian   
28     28           Spain                                Spanish   
29     29          Sweden                                Swedish   
30     30     Switzerland       French, German, Italian, Romansh   
31     31  United Kingdom                                English   

      Population     Capital                Currency  Phone     Int.  
0    8.4 million      Vienna              euro (EUR)     43      .at  
1     11 million    Brussels              euro (EUR)     32      .be  
2      7 million       Sofia     Bulgarian lev (BGN)    359      .bg  
3    4.3 million      Zagreb     Croatian kuna (HRK)    385      .hr  
4        800 000     Nicosia              euro (EUR)    357      .cy  
5     10 million      Prague      Czech koruna (CZK)    420      .cz  
6    5.6 million  Copenhagen      Danish krone (DKK)     45      .dk  
7    1.3 million     Tallinn              euro (EUR)    372      .ee  
8    5.4 million    Helsinki              euro (EUR)    358  .fi/.ax  
9     65 million       Paris              euro (EUR)     33      .fr  
10  82.5 million      Berlin              euro (EUR)     49      .de  
11    11 million      Athens              euro (EUR)     30      .gr  
12    10 million    Budapest  Hungarian forint (HUF)     36      .hu  
13       320 000   Reykjavik   Icelandic krona (ISK)    354      .is  
14   4.6 million      Dublin              euro (EUR)    353      .ie  
15  60.9 million        Rome              euro (EUR)     39      .it  
16     2 million        Riga      Latvian lats (LVL)    371      .lv  
17        36 300       Vaduz       Swiss franc (CHF)    423      .li  
18     3 million     Vilnius  Lithuanian litas (LTL)    370      .lt  
19       524 000  Luxembourg              euro (EUR)    352      .lu  
20       450 000    Valletta              euro (EUR)    356      .mt  
21  16.8 million   Amsterdam              euro (EUR)     31      .nl  
22     5 million        Oslo   Norwegian krone (NOK)     47      .no  
23  38.5 million      Warsaw      Polish ztoty (PLN)   

In [51]:
fire_data = pd.read_csv('fire.xls')
fire_data

fire_name                cause      month  year  \
0         Mendocino Complex  Under Investigation       July  2018   
1                    Thomas           Powerlines   December  2017   
2                     Cedar        Human Related    October  2003   
3                      Rush            Lightning     August  2012   
4                       Rim        Human Related     August  2013   
5                      Zaca        Human Related       July  2007   
6                      Carr        Human Related       July  2018   
7                  Matilija         Undetermined  September  1932   
8                     Witch           Powerlines    October  2007   
9   Klamath Theater Complex            Lightning       June  2008   
10              Marble Cone            Lightning       July  1977   
11                   Laguna           Powerlines  September  1970   
12            Basin Complex            Lightning       June  2008   
13                 Day Fire        Human Related  September  2006   
14                  Station        Human Related     August  2009   
15                Camp Fire           Powerlines   November  2018   
16                    Rough            Lightning       July  2015   
17                  Mcnally        Human Related       July  2002   
18       Stanislaus Complex            Lightning     August  1987   
19          Big Bar Complex            Lightning     August  1999   

                                               county   acres  structures  \
0   Colusa County, Lake County, Mendocino County &...  459123         280   
1                             Ventura & Santa Barbara  281893        1063   
2                                           San Diego  273246        2820   
3                                              Lassen  271911           0   
4                                            Tuolumne  257314         112   
5                                       Santa Barbara  240207           1   
6                        Shasta County,Trinity County  229651        1614   
7                                             Ventura  220000           0   
8                                           San Diego  197990        1650   
9                                            Siskiyou  192038           0   
10                                           Monterey  177866           0   
11                                          San Diego  175425         382   
12                                           Monterey  162818          58   
13                                            Ventura  162702          11   
14                                        Los Angeles  160557         209   
15                                              Butte  153336       18804   
16                                             Fresno  151623           4   
17                                             Tulare  150696          17   
18                                           Tuolumne  145980          28   
19                                            Trinity  140948           0   

    deaths  
0        1  
1        2  
2       15  
3        0  
4        0  
5        0  
6        8  
7        0  
8        2  
9        2  
10       0  
11       5  
12       0  
13       0  
14       2  
15      85  
16       0  
17       0  
18       1  
19       0

In [39]:
uniq_cause=fire_data["cause"].nunique()
uniq_cause

5

In [40]:
count_uniq_cause = fire_data['cause'].value_counts()
count_uniq_cause

Human Related          7
Lightning              7
Powerlines             4
Under Investigation    1
Undetermined           1
Name: cause, dtype: int64

In [53]:
max_deaths = fire_data['year'].value_counts().idxmax()
max_deaths

2018

In [64]:
people_died = fire_data['fire_name'][fire_data['deaths'] > 0].count()
people_died


10

In [67]:
sort_year= fire_data.sort_values('year',  ascending=False)
sort_year

fire_name                cause      month  year  \
0         Mendocino Complex  Under Investigation       July  2018   
15                Camp Fire           Powerlines   November  2018   
6                      Carr        Human Related       July  2018   
1                    Thomas           Powerlines   December  2017   
16                    Rough            Lightning       July  2015   
4                       Rim        Human Related     August  2013   
3                      Rush            Lightning     August  2012   
14                  Station        Human Related     August  2009   
9   Klamath Theater Complex            Lightning       June  2008   
12            Basin Complex            Lightning       June  2008   
5                      Zaca        Human Related       July  2007   
8                     Witch           Powerlines    October  2007   
13                 Day Fire        Human Related  September  2006   
2                     Cedar        Human Related    October  2003   
17                  Mcnally        Human Related       July  2002   
19          Big Bar Complex            Lightning     August  1999   
18       Stanislaus Complex            Lightning     August  1987   
10              Marble Cone            Lightning       July  1977   
11                   Laguna           Powerlines  September  1970   
7                  Matilija         Undetermined  September  1932   

                                               county   acres  structures  \
0   Colusa County, Lake County, Mendocino County &...  459123         280   
15                                              Butte  153336       18804   
6                        Shasta County,Trinity County  229651        1614   
1                             Ventura & Santa Barbara  281893        1063   
16                                             Fresno  151623           4   
4                                            Tuolumne  257314         112   
3                                              Lassen  271911           0   
14                                        Los Angeles  160557         209   
9                                            Siskiyou  192038           0   
12                                           Monterey  162818          58   
5                                       Santa Barbara  240207           1   
8                                           San Diego  197990        1650   
13                                            Ventura  162702          11   
2                                           San Diego  273246        2820   
17                                             Tulare  150696          17   
19                                            Trinity  140948           0   
18                                           Tuolumne  145980          28   
10                                           Monterey  177866           0   
11                                          San Diego  175425         382   
7                                             Ventura  220000           0   

    deaths  
0        1  
15      85  
6        8  
1        2  
16       0  
4        0  
3        0  
14       2  
9        2  
12       0  
5        0  
8        2  
13       0  
2       15  
17       0  
19       0  
18       1  
10       0  
11       5  
7        0

In [73]:
menesiai = {1: 'January',
  2: 'February',
  3: 'March',
  4: 'April',
  5: 'May',
  6: 'June',
  7: 'July',
  8: 'August',
  9: 'September',
  10: 'October',
  11: 'November',
  12: 'December'}

def months_to_numbers(month_name):
    for month_number, name in menesiai.items():
        if name == month_name:
            return month_number


In [79]:
fire_data['month'] = fire_data['month'].apply(months_to_numbers)
fire_data


fire_name                cause  month  year  \
0         Mendocino Complex  Under Investigation      7  2018   
1                    Thomas           Powerlines     12  2017   
2                     Cedar        Human Related     10  2003   
3                      Rush            Lightning      8  2012   
4                       Rim        Human Related      8  2013   
5                      Zaca        Human Related      7  2007   
6                      Carr        Human Related      7  2018   
7                  Matilija         Undetermined      9  1932   
8                     Witch           Powerlines     10  2007   
9   Klamath Theater Complex            Lightning      6  2008   
10              Marble Cone            Lightning      7  1977   
11                   Laguna           Powerlines      9  1970   
12            Basin Complex            Lightning      6  2008   
13                 Day Fire        Human Related      9  2006   
14                  Station        Human Related      8  2009   
15                Camp Fire           Powerlines     11  2018   
16                    Rough            Lightning      7  2015   
17                  Mcnally        Human Related      7  2002   
18       Stanislaus Complex            Lightning      8  1987   
19          Big Bar Complex            Lightning      8  1999   

                                               county   acres  structures  \
0   Colusa County, Lake County, Mendocino County &...  459123         280   
1                             Ventura & Santa Barbara  281893        1063   
2                                           San Diego  273246        2820   
3                                              Lassen  271911           0   
4                                            Tuolumne  257314         112   
5                                       Santa Barbara  240207           1   
6                        Shasta County,Trinity County  229651        1614   
7                                             Ventura  220000           0   
8                                           San Diego  197990        1650   
9                                            Siskiyou  192038           0   
10                                           Monterey  177866           0   
11                                          San Diego  175425         382   
12                                           Monterey  162818          58   
13                                            Ventura  162702          11   
14                                        Los Angeles  160557         209   
15                                              Butte  153336       18804   
16                                             Fresno  151623           4   
17                                             Tulare  150696          17   
18                                           Tuolumne  145980          28   
19                                            Trinity  140948           0   

    deaths  
0        1  
1        2  
2       15  
3        0  
4        0  
5        0  
6        8  
7        0  
8        2  
9        2  
10       0  
11       5  
12       0  
13       0  
14       2  
15      85  
16       0  
17       0  
18       1  
19       0

In [19]:
import requests
url = 'https://lt.wikipedia.org/wiki/Sąrašas:Lietuvos_miestai_pagal_gyventojus'
text = requests.get(url).content
cities = pd.read_html(text)
find_cities = cities[0]
find_cities

Eilė    Miestas  2021 m.  2011 m.  2001 m.  1989 m.  1979 m.   1970 m.  \
0       1    Vilnius   546155   524406   542287   576747   475825  372100.0   
1       2     Kaunas   298753   315993   378943   418087   368649  305116.0   
2       3   Klaipėda   152008   162360   192954   202929   176648  140012.0   
3       4   Šiauliai   100653   109328   133883   145629   118724   93057.0   
4       5  Panevėžys    89110    99690   119749   126483   102303   73328.0   
..    ...        ...      ...      ...      ...      ...      ...       ...   
98     99   Užventis      600      833      898     1149     1229    1406.0   
99    100    Dusetos      531      717      914     1185     1393    1578.0   
100   101  Kavarskas      503      666      809      972     1113    1256.0   
101   102  Troškūnai      389      451      525      672     1174    1434.0   
102   103   Panemunė      217      274      329      398      506     492.0   

      1959 m. 1923 m.  1897 m. Tankumas (2019)  
0    236078.0  167400  154532*    1374 žm./km²  
1    219287.0   92446   70920*    1843 žm./km²  
2     90521.0   35845    20100    1356 žm./km²  
3     59722.0   21387   16128*    1251 žm./km²  
4     41096.0   19197   12968*    1590 žm./km²  
..        ...     ...      ...             ...  
98     1704.0     (?)      945     260 žm./km²  
99     1806.0    1164     1278     316 žm./km²  
100    1287.0    1041     1546     443 žm./km²  
101    1495.0    1252     1000     458 žm./km²  
102     539.0     637      NaN     112 žm./km²  

[103 rows x 12 columns]

In [178]:
set_city = find_cities.set_index('Miestas')
set_city

Eilė  2021 m.  2011 m.  2001 m.  1989 m.  1979 m.  \
Miestas                                                                  
Vilnius                 1   546155   524406   542287   576747   475825   
Kaunas                  2   298753   315993   378943   418087   368649   
Klaipėda                3   152008   162360   192954   202929   176648   
Šiauliai                4   100653   109328   133883   145629   118724   
Panevėžys               5    89110    99690   119749   126483   102303   
Alytus                  6    52727    59964    71491    73015    55509   
Marijampolė             7    36727    41051    48675    50887    38824   
Mažeikiai               8    33101    37020    42675    43547    25779   
Jonava                  9    27381    30650    34954    36520    28413   
Utena                  10    25343    28997    33860    34430    23461   
Kėdainiai              11    23461    26648    32048    33840    27886   
Telšiai                12    22642    25540    31460    33351    26369   
Ukmergė                13    21258    23878    28759    30410    26601   
Tauragė                14    21203    24389    29124    30119    25966   
Visaginas              15    19446    22361    29554    32438     6212   
Plungė                 16    17543    20041    23436    22535    18829   
Kretinga               17    17249    19010    21423    19516    16197   
Palanga                18    16746    15732    17623    17571    11980   
Šilutė                 19    15952    17775    21476    21179    16000   
Radviliškis            20    15103    17254    20339    21263    19232   
Gargždai               21    15065    15021    15212    13409    10042   
Druskininkai           22    12908    14764    18233    18943    12464   
Rokiškis               23    11770    14351    16746    17826    13192   
Elektrėnai             24    11255    12012    14050    15871     8466   
Kuršėnai               25    10916    11963    14197    14796    13223   
Biržai                 26    10734    12465    15262    15907    14401   
Garliava               27    10366    11264    13322    12420     9418   
Vilkaviškis            28    10286    11547    13283    13829    11836   
Jurbarkas              29    10186    11232    13797    14310    10644   
Grigiškės              30     9950    10867    11448    11610     8259   
Raseiniai              31     9865    11203    12541    13211    11403   
Lentvaris              32     9713    11105    11773    12964    10167   
Prienai                33     8796     9867    11353    11909     9398   
Anykščiai              34     8697    10575    11958    12758    10325   
Joniškis               35     8612     9899    11329    11773     9303   
Kaišiadorys            36     8380     8664    10002    10964     9022   
Varėna                 37     8202     9240    10845    12291     8015   
Naujoji Akmenė         38     7985     9300    12345    13590    14195   
Kelmė                  39     7688     9150    10900    11557     9073   
Šalčininkai            40     6857     6358     6722     6480     3857   
Pasvalys               41     6451     7523     8709     9071     7370   
Kupiškis               42     6218     7206     8451     8786     6307   
Zarasai                43     6077     7165     8365     8916     7250   
Širvintos              44     5827     6415     7273     7442     5146   
Molėtai                45     5782     6434     7221     6843     5165   
Kazlų Rūda             46     5590     6635     7401     7715     6312   
Skuodas                47     5508     6513     7896     8730     7269   
Šakiai                 48     5462     6051     6795     7226     5955   
Trakai                 49     5426     4933     5725     6703     5763   
Ignalina               50     5106     6007     6591     6872     4927   
Pabradė                51     4918     5994     6525     7360     6655   
Nemenčinė              52     4831     5054     5892     5612     4075   
Švenčionėliai          53

In [179]:
set_city.drop('Eilė', axis=1, inplace=True)
set_city.drop('Tankumas (2019)', axis=1, inplace=True)

In [181]:
set_city

2021 m.  2011 m.  2001 m.  1989 m.  1979 m.   1970 m.  \
Miestas                                                                      
Vilnius               546155   524406   542287   576747   475825  372100.0   
Kaunas                298753   315993   378943   418087   368649  305116.0   
Klaipėda              152008   162360   192954   202929   176648  140012.0   
Šiauliai              100653   109328   133883   145629   118724   93057.0   
Panevėžys              89110    99690   119749   126483   102303   73328.0   
Alytus                 52727    59964    71491    73015    55509   28074.0   
Marijampolė            36727    41051    48675    50887    38824   28763.0   
Mažeikiai              33101    37020    42675    43547    25779   13468.0   
Jonava                 27381    30650    34954    36520    28413   14438.0   
Utena                  25343    28997    33860    34430    23461   13319.0   
Kėdainiai              23461    26648    32048    33840    27886   19677.0   
Telšiai                22642    25540    31460    33351    26369   20220.0   
Ukmergė                21258    23878    28759    30410    26601   21663.0   
Tauragė                21203    24389    29124    30119    25966   19461.0   
Visaginas              19446    22361    29554    32438     6212       NaN   
Plungė                 17543    20041    23436    22535    18829   13560.0   
Kretinga               17249    19010    21423    19516    16197   13091.0   
Palanga                16746    15732    17623    17571    11980    8797.0   
Šilutė                 15952    17775    21476    21179    16000   12401.0   
Radviliškis            15103    17254    20339    21263    19232   16841.0   
Gargždai               15065    15021    15212    13409    10042    6414.0   
Druskininkai           12908    14764    18233    18943    12464   11160.0   
Rokiškis               11770    14351    16746    17826    13192    9146.0   
Elektrėnai             11255    12012    14050    15871     8466    6646.0   
Kuršėnai               10916    11963    14197    14796    13223   11468.0   
Biržai                 10734    12465    15262    15907    14401   11385.0   
Garliava               10366    11264    13322    12420     9418    5587.0   
Vilkaviškis            10286    11547    13283    13829    11836    8566.0   
Jurbarkas              10186    11232    13797    14310    10644    6575.0   
Grigiškės               9950    10867    11448    11610     8259    4991.0   
Raseiniai               9865    11203    12541    13211    11403    8931.0   
Lentvaris               9713    11105    11773    12964    10167    8059.0   
Prienai                 8796     9867    11353    11909     9398    7841.0   
Anykščiai               8697    10575    11958    12758    10325    8238.0   
Joniškis                8612     9899    11329    11773     9303    7522.0   
Kaišiadorys             8380     8664    10002    10964     9022    4701.0   
Varėna                  8202     9240    10845    12291     8015    4494.0   
Naujoji Akmenė          7985     9300    12345    13590    14195   10175.0   
Kelmė                   7688     9150    10900    11557     9073    7087.0   
Šalčininkai             6857     6358     6722     6480     3857    1753.0   
Pasvalys                6451     7523     8709     9071     7370    6027.0   
Kupiškis                6218     7206     8451     8786     6307    4876.0   
Zarasai                 6077     7165     8365     8916     7250    6605.0   
Širvintos               5827     6415     7273     7442     5146    3073.0   
Molėtai                 5782     6434     7221     6843     5165    3665.0   
Kazlų Rūda              5590     6635     7401     7715     6312    4397.0   
Skuodas                 5508     6513     7896     8730     7269    4693.0   
Šakiai                  5462     6051     6795     7226     5955    4227.0   
Trakai                  5426     4933     5725     6703     5763    4667.0   
Ignalina                5106     6007     6

In [182]:
year_list = set_city.columns.tolist()
year_list

['2021\xa0m.',
 '2011\xa0m.',
 '2001\xa0m.',
 '1989\xa0m.',
 '1979\xa0m.',
 '1970\xa0m.',
 '1959\xa0m.',
 '1923\xa0m.',
 '1897\xa0m.']

In [183]:
new_list = []
for item in year_list:
    fixed = item.replace('\xa0m.', '')
    new_list.append(fixed)

set_city.columns = new_list
new_list

['2021', '2011', '2001', '1989', '1979', '1970', '1959', '1923', '1897']

In [184]:
set_city.fillna(0, inplace=True)



In [185]:
set_city.replace(['(??)', '(?)'], int(0), inplace=True)

In [186]:
set_city

2021    2011    2001    1989    1979      1970  \
Miestas                                                                 
Vilnius              546155  524406  542287  576747  475825  372100.0   
Kaunas               298753  315993  378943  418087  368649  305116.0   
Klaipėda             152008  162360  192954  202929  176648  140012.0   
Šiauliai             100653  109328  133883  145629  118724   93057.0   
Panevėžys             89110   99690  119749  126483  102303   73328.0   
Alytus                52727   59964   71491   73015   55509   28074.0   
Marijampolė           36727   41051   48675   50887   38824   28763.0   
Mažeikiai             33101   37020   42675   43547   25779   13468.0   
Jonava                27381   30650   34954   36520   28413   14438.0   
Utena                 25343   28997   33860   34430   23461   13319.0   
Kėdainiai             23461   26648   32048   33840   27886   19677.0   
Telšiai               22642   25540   31460   33351   26369   20220.0   
Ukmergė               21258   23878   28759   30410   26601   21663.0   
Tauragė               21203   24389   29124   30119   25966   19461.0   
Visaginas             19446   22361   29554   32438    6212       0.0   
Plungė                17543   20041   23436   22535   18829   13560.0   
Kretinga              17249   19010   21423   19516   16197   13091.0   
Palanga               16746   15732   17623   17571   11980    8797.0   
Šilutė                15952   17775   21476   21179   16000   12401.0   
Radviliškis           15103   17254   20339   21263   19232   16841.0   
Gargždai              15065   15021   15212   13409   10042    6414.0   
Druskininkai          12908   14764   18233   18943   12464   11160.0   
Rokiškis              11770   14351   16746   17826   13192    9146.0   
Elektrėnai            11255   12012   14050   15871    8466    6646.0   
Kuršėnai              10916   11963   14197   14796   13223   11468.0   
Biržai                10734   12465   15262   15907   14401   11385.0   
Garliava              10366   11264   13322   12420    9418    5587.0   
Vilkaviškis           10286   11547   13283   13829   11836    8566.0   
Jurbarkas             10186   11232   13797   14310   10644    6575.0   
Grigiškės              9950   10867   11448   11610    8259    4991.0   
Raseiniai              9865   11203   12541   13211   11403    8931.0   
Lentvaris              9713   11105   11773   12964   10167    8059.0   
Prienai                8796    9867   11353   11909    9398    7841.0   
Anykščiai              8697   10575   11958   12758   10325    8238.0   
Joniškis               8612    9899   11329   11773    9303    7522.0   
Kaišiadorys            8380    8664   10002   10964    9022    4701.0   
Varėna                 8202    9240   10845   12291    8015    4494.0   
Naujoji Akmenė         7985    9300   12345   13590   14195   10175.0   
Kelmė                  7688    9150   10900   11557    9073    7087.0   
Šalčininkai            6857    6358    6722    6480    3857    1753.0   
Pasvalys               6451    7523    8709    9071    7370    6027.0   
Kupiškis               6218    7206    8451    8786    6307    4876.0   
Zarasai                6077    7165    8365    8916    7250    6605.0   
Širvintos              5827    6415    7273    7442    5146    3073.0   
Molėtai                5782    6434    7221    6843    5165    3665.0   
Kazlų Rūda             5590    6635    7401    7715    6312    4397.0   
Skuodas                5508    6513    7896    8730    7269    4693.0   
Šakiai                 5462    6051    6795    7226    5955    4227.0   
Trakai                 5426    4933    5725    6703    5763    4667.0   
Ignalina               5106    6007    6591    6872    4927    3515.0   
Pabradė                4918    5994    6525    7360    6655    5919.0   
Nemenčinė              4831    5054    5892    5612    4075    3208.0   
Švenčionėliai          4748    5771    6923    7712    6566    5964.0   
Šilalė  

In [188]:
def remove_star(text):
    if type(text) == str:
        return int(text.replace('*', ''))
    return text

In [208]:
set_city.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103 entries, Vilnius to Panemunė
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2021    103 non-null    int64
 1   2011    103 non-null    int64
 2   2001    103 non-null    int64
 3   1989    103 non-null    int64
 4   1979    103 non-null    int64
 5   1970    103 non-null    int64
 6   1959    103 non-null    int64
 7   1923    103 non-null    int64
 8   1897    103 non-null    int64
dtypes: int64(9)
memory usage: 12.1+ KB


In [192]:
def remove_zero(f):
    return int(f)

In [193]:
def make_int(f):
    return int(f)

In [194]:
set_city['1959'] = set_city['1959'].apply(remove_zero)

In [195]:
set_city['1959']

Miestas
Vilnius                236078
Kaunas                 219287
Klaipėda                90521
Šiauliai                59722
Panevėžys               41096
Alytus                  12350
Marijampolė             19621
Mažeikiai                7957
Jonava                   5005
Utena                    7158
Kėdainiai               10580
Telšiai                 13460
Ukmergė                 14880
Tauragė                 12041
Visaginas                   0
Plungė                   3672
Kretinga                 9690
Palanga                  5685
Šilutė                   8969
Radviliškis             12613
Gargždai                 1524
Druskininkai             5765
Rokiškis                 5520
Elektrėnai                  0
Kuršėnai                 9099
Biržai                   8624
Garliava                 2489
Vilkaviškis              5072
Jurbarkas                4412
Grigiškės                2559
Raseiniai                6242
Lentvaris                4216
Prienai                  5423
An

In [197]:
set_city['1970'] = set_city['1970'].apply(remove_zero)

In [199]:
set_city['1923'] = set_city['1923'].apply(make_int)

In [207]:
set_city['1897'] = set_city['1897'].apply(remove_star)

In [177]:
set_city.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103 entries, Vilnius to Panemunė
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   2021    103 non-null    int64  
 1   2011    103 non-null    int64  
 2   2001    103 non-null    int64  
 3   1989    103 non-null    int64  
 4   1979    103 non-null    int64  
 5   1970    103 non-null    float64
 6   1959    103 non-null    int64  
 7   1923    103 non-null    object 
 8   1897    103 non-null    object 
dtypes: float64(1), int64(6), object(2)
memory usage: 12.1+ KB
